FROM ruby:3.2.3

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN apt-get update -qq && apt-get install -y \
    postgresql-client \
    nodejs \
    yarn \
    vim \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile ./

RUN bundle install

COPY . .

CMD ["bash"]